<a href="https://colab.research.google.com/github/bsudharshan2001/MyRespository/blob/master/College/Semester-5/19CSE305-MachineLearning/Lab%202/CB.EN.U4CSE19008_ML_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python Basics : Excercises**
----
B Sudharshan - CB.EN.U4CSE19008



In [7]:
#Question 1
def prime(n,end):
  for i in range(2,end):
    if(n%i==0):
      return False
  return True  
start=int(input('Enter Starting no: '))
end=int(input('Enter Ending no: '))
for i in range(start,end):
  if(prime(i,end)):
      print(i)   

Enter Starting no: 5
Enter Ending no: 10


In [10]:
#Question 2
word=input("Enter String: ")
lst=word.split()
freq=[]
j=0
sum=0
for i in lst:
  freq.append(lst.count(i))
for j in freq:
  sum=sum+j
want=input('Word? ')
ans=(freq[lst.index(want)]/sum)*100
print(ans)

Enter String: hi hello hi
Word? hi


In [17]:
#Question 3
import math
n=int(input('Enter no: '))
n1=5*n*n+4
n2=5*n*n-4
s1=math.sqrt(n1)
s2=math.sqrt(n2)
if((s1*s1==n1) or (s2*s2==n2)):
  print("Is a Fibonacci")



Enter no: 5
Is a Fibonacci


In [21]:
#Question 4
n=int(input('Enter a no:'))
temp=n
while(temp>0):
  dig=temp%10
  if((dig!=0) and (n%dig==0)):
    print('No not divisible by digits')
  temp=temp//10
print('No Divisible')

Enter a no:35
No not divisible by digits
No Divisible


In [ ]:
#Question 5
n=int(input())
for i in range(0,n):
  e=int(input())
k=int(input())


**NumPy Questions**

In [15]:
#Question 1
import numpy as np
q1 = np.random.randint(3,10,(4,5))
print(q1)

[[3 3 3 4 6]
 [4 9 6 9 4]
 [7 7 8 9 7]
 [7 8 8 3 9]]


In [14]:
#Question 2
import numpy as np
q2 = np.random.randint(0,10,(10))
print(q2)
q2.reshape(2,5)
print(q2)

[4 2 2 9 3 6 2 8 9 6]
[4 2 2 9 3 6 2 8 9 6]


In [11]:
#Question 3
import numpy as np
q3 = [97,88,102,99,95]
q3 = np.array(q3)
print(q3)
for i in q3:
  i = (i - 32)*(5/9)
print(q3)

[ 97  88 102  99  95]


In [12]:
#Question 4
import numpy as np
q4 = np.random.randint(2,8,(2,3,5))
print(q4.itemsize)
print(q4.shape)
print(q4.size)

8
(2, 3, 5)
30


In [13]:
#Question 5
import numpy as np
q5 = np.random.randint(3,8,(3,4))
print(q5)
print(q5[1:3,2:4])

[[3 3 7 3]
 [4 7 7 4]
 [4 7 7 5]]
[[7 4]
 [7 5]]
